### ISSUE TITLE
Feature Request: Add flag to bypass version check

### ISSUE THREAD

**Issue by upstart-swiss** [demisto/demisto-sdk#1062]
There's times I want to parallelize demisto-sdk, and the version check is both worthless and ends up hitting api limits. I'd like to request a `--no-version-check` option to bypass this (and preferably any other unnecessary checks like the git repo).

**Comment by glicht** [comment]
@upstart-swiss sorry for the delayed response. Seems that we missed this one. 

You can use the environment variable:
```
DEMISTO_SDK_SKIP_VERSION_CHECK=yes
```
