### ISSUE TITLE
Dependency problems with colorama

### ISSUE THREAD

**Issue by janihy** [demisto/demisto-sdk#1377]
According to pip, demisto-sdk requires colorama==0.4.1. This requirement is unnecessarily strict and prevents installing semgrep, which depends on colorama>=0.4.3.

```
$ pip3 install demisto-sdk==1.4.0 semgrep==0.56.0
...
ERROR: Cannot install demisto-sdk==1.4.0 and semgrep==0.56.0 because these package versions have conflicting dependencies.

The conflict is caused by:
    demisto-sdk 1.4.0 depends on colorama==0.4.1
    semgrep 0.56.0 depends on colorama>=0.4.3

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/user_guide/#fixing-conflicting-dependencies
$
```

[Colorama](https://pypi.org/project/colorama/) seems to be a cross-platform compatibility library for colors in terminal output so maybe this requirement could be changed to e.g. >=0.4.1.

**Comment by roysagi** [comment]
@janihy - Thank you for reporting this. We are working on making our requirements more strict in some areas to prevent collisions with the content repository. This does not seem like such a case though so we should loosen the requirement.
