### ISSUE TITLE
Missing Readme results in AttributeError

### ISSUE THREAD

**Issue by upstart-swiss** [demisto/demisto-sdk#1418]
When file contents are null, or can't be read, this throws false and causes the readme line to fail on the lower()

https://github.com/demisto/demisto-sdk/blob/eca8d7d8ee6520d68bd22cbe87bead6b10d6d3e4/demisto_sdk/commands/common/hook_validations/pack_unique_files.py#L130

https://github.com/demisto/demisto-sdk/blob/eca8d7d8ee6520d68bd22cbe87bead6b10d6d3e4/demisto_sdk/commands/common/hook_validations/pack_unique_files.py#L192-L193

```
  File "/Users/chrisschafer/gits/demisto_prod/venv/lib/python3.8/site-packages/demisto_sdk/commands/common/hook_validations/pack_unique_files.py", line 193, in validate_pack_readme_and_pack_description
    readme_content = readme.lower().strip()
AttributeError: 'bool' object has no attribute 'lower'
```

Recommendation: Return a string, or type-check before performing the operation. I don't know how often this is used or if there's a dependency on it returning False elsewhere, so I don't want to make an unknowning PR

**Comment by roysagi** [comment]
@upstart-swiss - Thanks for noting this issue. This seems like a mistake, we should catch an empty pack readme and notify the user that it is empty and he should fill it.

**Comment by roysagi** [comment]
After some additional research, it seems there is a check for the file not being empty.
The issue here is the case the file does not exist which creates this error - indeed getting null thus creating this chain of events.

I'll add an existence check for the readme file and add an error message accordingly.
