### ISSUE TITLE
Github lookup hardcoded to Master

### ISSUE THREAD

**Issue by upstart-swiss** [demisto/demisto-sdk#1509]
https://github.com/demisto/demisto-sdk/blob/a69ef95b114269a480407308e3b10b33906768b0/demisto_sdk/commands/common/constants.py#L886

The base branch for a repo isn't necessarily master - Github has defaulted to `main` for new repos. This breaks compatibility with newer repos.

**Comment by upstart-swiss** [comment]
Another location causing failures on a private repo w/ an upstream of `main`:
https://github.com/demisto/demisto-sdk/blob/b0597dd05a0d2f5904f5b0013098797bafe3fe3f/demisto_sdk/commands/common/hook_validations/pack_unique_files.py#L507

When `prev_ver` is set to something other than `master`, it should be validated against the `prev_ver`

**Comment by anara123** [comment]
resolved
