### ISSUE TITLE
Putting token in params and then logging the URL error exposes secrets

### ISSUE THREAD

**Issue by upstart-swiss** [demisto/demisto-sdk#1526]
This action exposes secrets on errors.

https://github.com/demisto/demisto-sdk/blob/b0597dd05a0d2f5904f5b0013098797bafe3fe3f/demisto_sdk/commands/common/tools.py#L231

**Comment by tomneeman151293** [comment]
Managed to reproduce. Opening an issue and a fix to not expose token upon failure.
