### ISSUE TITLE
Upload command fails behind proxy

### ISSUE THREAD

**Issue by dylan8902** [demisto/demisto-sdk#1620]
An upload to a server behind a proxy fails as no configuration is passed through to the rest client and the default is `None`

https://github.com/demisto/demisto-sdk/blob/141de2acfcc4de136fabfb01f501016e65ff7ed3/demisto_sdk/commands/upload/uploader.py#L99

**Comment by dorschw** [comment]
The issue is [solved](https://github.com/demisto/demisto-py/pull/91) in the `demisto-py` package (that the demisto-SDK uses), please update it using `pip install demisto-py --upgrade`. Please let us know if there are any other issues.

**Comment by dylan8902** [comment]
Brilliant thanks
