### ISSUE TITLE
State management when using demisto-sdk and GUI interchangeably 

### ISSUE THREAD

**Issue by nicolaipre** [demisto/demisto-sdk#1685]
We are multiple users with different levels of technical backgrounds using Demisto/XSOAR at my workplace, where some prefer using the demisto-sdk, and some prefer using the XSOAR GUI to make configuration changes. 

I noticed that the demisto-sdk does not seem to track state (?), and simply overwrites any changes made in the GUI after the last demisto-sdk upload. 

**Example scenario:**
1. The last demisto-sdk upload with changes to integration/script/automation `X` was done 2020-10-01 by user Alice.
2. On 2020-10-10, Bob made changes to integration/script/automation `X` using the XSOAR GUI. 
3. Alice then makes some changes to integration/script/autiomation `Y` using demisto-sdk, and pushes the whole Pack (including both `X` and `Y`), resulting in overwriting Bob's work done 2020-10-10 on `X` since no error messages were given that content was out of sync between demisto-sdk and XSOAR GUI. 
4. Bob now has lost the changes he made previously due to the overwrite, and the XSOAR workflow is now failing.

My question is therefore: Is there any way to keep track of content versions using demisto-sdk?

The only way I have found a somewhat working solution to this is by always pulling all data using `demisto-sdk download --all-custom-content -o Packs/somepack` before making any changes. The problem doing this is that if you have separated your custom content in multiple packs, you have to manually sort out all the content downloaded to the pack `somewhat` into the correct separate packs every time you want to make sure you are up to date.

**Comment by GuyAfik** [comment]
@nicolaipre if this is still relevant, please reopen with relevant details for today.
