### ISSUE TITLE
Download Regex Flag Usage

### ISSUE THREAD

**Issue by tbailey25** [demisto/demisto-sdk#1803]
When running `demisto-sdk download` with the `--regex` flag, should it be assumed that all content should be downloaded without having to supply the `--all-custom-content` flag? Currently when providing the `--regex` flag without `--all-custom-content` nothing is downloaded, and there is no indication as to why.

```
$ demisto-sdk download -r "^Test" -o Packs/Test
You are using demisto-sdk 1.5.6.dev31.
however version 1.5.5 is available.
You should consider upgrading via "pip3 install --upgrade demisto-sdk" command.

Demisto instance: Enumerating objects: 0, done.
Demisto instance: Receiving objects: 100% (0/0), done.
```
```
$ demisto-sdk download -r "^Test" -o Packs/Test -a
You are using demisto-sdk 1.5.6.dev31.
however version 1.5.5 is available.
You should consider upgrading via "pip3 install --upgrade demisto-sdk" command.

Demisto instance: Enumerating objects: 1, done.
Demisto instance: Receiving objects: 100% (1/1), done.

- Added Widget "Test Widget1"

1 file added.
```
My thoughts would be to either error in the `verify_flags()` method if `--regex` is provided without `--all-custom-content`
https://github.com/demisto/demisto-sdk/blob/89519b985a858317a6392d73e8f4d92032de0e4d/demisto_sdk/commands/download/downloader.py#L123

Or have `--regex` just assume `--all-custom-content`.

**Comment by ChanochShayner** [comment]
@tbailey25 
Fixed, should be in the new SDK release.

**Comment by tbailey25** [comment]
Awesome, thanks!
