### ISSUE TITLE
Demisto-SDK Support for Multiple XSOAR Servers

### ISSUE THREAD

**Issue by Pinger77** [demisto/demisto-sdk#1896]
This request is not to report a bug or issue, but rather an idea for a new feature. Currently the Demisto-SDK will only connect to 1 XSOAR server at a time without utilizing other methods to change DEMISTO_BASE_URL and DEMISTO_API_KEY. When running several of the SDK commands that interface with an XSOAR server (upload/download/etc), it would be nice to also be able to pick the server you are uploading to/downloading from/etc. With the creation of the CI/CD content pack, and the large role the Demisto-SDK plays in the process, having the ability to change XSOAR servers quickly would make it easier to deploy on different environments (Test/Prod) with the flip of a switch.

**Comment by ChanochShayner** [comment]
@dorschw @bakatzir

**Comment by tbailey25** [comment]
Would it be possible to define multiple environment variables and have an argument to the `demisto-sdk` commands to specify which one to use?

Eg.
```
$ cat .env
DEMISTO_BASE_URL_DEV=<url1>
DEMISTO_API_KEY_DEV=<key1>
DEMISTO_BASE_URL_PROD=<url2>
DEMISTO_API_KEY_PROD=<key2>
```
```
$ demisto-sdk download -i <input> -o <output> --server dev
```

And possibly prompt the user for which one to use if not specified via the cli?

**Comment by dorschw** [comment]
Thank you for the suggestions @Pinger77 @ping@tbailey25, we'll consider adding this feature in future releases.

**Comment by tbailey25** [comment]
If that's the direction that should be taken, then I would suggest a function that will clean the environment afterwards. If the .env files are sourced prior to the `demisto-sdk` command then you risk leaving the variables in the environment and then forgetting to source a different .env file on the next execution of `demisto-sdk`. This could lead to taking action against a XSOAR server that you did not intend.

```bash
demisto-sdk-dev () {
  source .env-dev
  demisto-sdk "$@"
  unset DEMISTO_BASE_URL
  unset DEMISTO_API_KEY
}
```

**Comment by PaulBartruff** [comment]
> 

I use separate shell scripts that I source before using the sdk, and I often forget which one I left off at!  Also, when in vscode, it will pop open a new terminal and run before I have sourced my API and BASE, so I must then source and re-run the command.

**Comment by PaulBartruff** [comment]
I like the idea of an identity flag, if it's set on the command line the sdk will open an INI file for the specific settings similar to awscli.  If the flag is not there it will try and use the environment variables.

**Comment by dorschw** [comment]
tracked internally as [CIAC-4438](https://jira-hq.paloaltonetworks.local/browse/CIAC-4438)

**Comment by JudahSchwartz** [comment]
closing as there doesnt seem to be high demand for this and the workaround provided is arguably a better solution
