### ISSUE TITLE
.pack-ignore No support for all errors & multiple files

### ISSUE THREAD

**Issue by lesleyxyz** [demisto/demisto-sdk#1898]
According to the [validate](https://github.com/demisto/demisto-sdk/blob/master/demisto_sdk/commands/validate/README.md) documentation, the only error I can ignore is `BA101`.
From my testing this seems to be true as I can't ignore errors like `ST107`

In addition to that, it would also be handy to set a global default for all files in the `.pack-ignore` file

**Comment by ChanochShayner** [comment]
@dorschw @bakatzir

**Comment by ChanochShayner** [comment]
@lesleyxyz This is the list of all the ignore errors - https://github.com/demisto/demisto-sdk/blob/65f6ed3cb1c97f3b7ab3ef37b45e6b4bc94ffb60/demisto_sdk/commands/common/errors.py#L16

**Comment by idovandijk** [comment]
@lesleyxyz can you please elaborate on what should be available? If I understood correctly you want to be able to ignore any/all error, for any/all files? Any by global default you mean that by default the ignored code would be applied to all pack files?
it does happen from time to time that we need to ignore non-ignorable errors, but whether we want to permit all is a question we need to review. @dorschw we can review all the errors together and see whether we can make any change

**Comment by dorschw** [comment]
will be handled in https://github.com/demisto/etc/issues/48000 / ([CIAC-495](https://jira-hq.paloaltonetworks.local/browse/CIAC-495))

**Comment by dorschw** [comment]
Validations cannot be ignored when they're necessary for the content to function properly.

@K-Yo, @lesleyxyz - to vote for this issue to be prioritized (or others opened in the repo), please open it on our [Aha](https://xsoar.ideas.aha.io/ideas), using the `demisto-sdk` label.
