### ISSUE TITLE
The .env file isn't loaded from the cwd

### ISSUE THREAD

**Issue by nicolas-rdgs** [demisto/demisto-sdk#1912]
According to my understanding, demisto-sdk is supposed to load the .env file in the folder where we are.

However, this doesn't work on my side and after doing some research, I saw that the dotenv library doesn't use the current working directory by default _(see: find_dotenv() in load_dotenv())_ and tries to find the file from the file that calls the command, so this file: "`/usr/local/lib/python3.9/dist-packages/demisto_sdk/__main__.py`" and seek for `/usr/local/lib/python3.9/dist-packages/demisto_sdk/.env` which is incorrect.

So, I tried to pass True to `usecwd` parameter of `find_dotenv()` function in dotenv library or to copy the env file in the above directory and all working fine. But this library do not allow to pass this parameter into load_dotenv(), badly.

Has anyone encountered the same problem?

EDIT: This could be a quick fix:

```python
@pass_config
def main(config, version, release_notes):
    import dotenv
    dotenv.load_dotenv(os.getcwd() + '/.env')  # Load a .env file from the cwd.
```

**Comment by dorschw** [comment]
@jochman wdyt?

**Comment by jochman** [comment]
I think that he's right, and we should fix it :)

Thank you, Nicolas.

**Comment by nicolas-rdgs** [comment]
Thanks you too!
