### ISSUE TITLE
Validate Prompts Inconsistent Default Behavior

### ISSUE THREAD

**Issue by tbailey25** [demisto/demisto-sdk#1917]
When running `validate` on Playbooks the user is occasionally prompted to add missing information. When prompted the prompt ends with `[Y/n]` which would indicate that `Y` is the default selection and simply pressing return will chose the default. This is not the case when prompted to add a description to the playbook.

```
No description is specified for this playbook, would you like to add a description? [Y/n]

Invalid input, would you like to add a description? [Y/n]
y
Please enter the description
```
However, when prompted to add a `fromversion`, the default selection is selected by simply pressing return.
```
No fromversion is specified for this playbook, would you like me to update for you? [Y/n]

Please specify the desired version X.X.X
```

Would it be possible to get the behavior of the description prompt updated, or at a minimum the prompt not to indicate a default selection?

**Comment by dorschw** [comment]
Hi Tyler, thanks for letting us know of this issue

We'll look into it and update you by early next week.

**Comment by dorschw** [comment]
Opened [internal issue](https://github.com/demisto/etc/issues/46982)
