### ISSUE TITLE
Demisto-sdk version 1.5.2 - 1.6.1 fails when uploading lists

### ISSUE THREAD

**Issue by nb-pdragoi** [demisto/demisto-sdk#1923]
Starting from version 1.5.2 of the sdk, together with server 6.5 of XSOAR, lists are content items, meaning they are support for upload, download etc. However, this is not done properly.

Trying to upload a list item gives the error **'DefaultApi' object has no attribute 'generic_request_func'**. This is not dependant on the content in the list.
Taking a look at the code, it seems this content type was rushed and not implemented correctly. Because the result of the **upload** command is a tuple, it also failes to convert to string if **verbose** mode is enabled, causing the summary for upload to disappear if the command to upload the list is given to the pack (not the individual list)

It is possible that the same applies to jobs, since they share some of the code, but I haven't tested personally.
I have talked with @ChanochShayner on slack, he has some details.

**Comment by dorschw** [comment]
Hi Paul, thanks for opening an issue

Regarding the lists, we're opening an internal issue and will update here with the conclusion.
Jobs are not yet supported as content items on the XSOAR side (but only on the SDK). We'll take a look to make sure the issue you described does not reproduce there as well.

**Comment by dorschw** [comment]
Closing as the fix was merged, please reopen if the issue persist
