### ISSUE TITLE
Allow setting Tenant name when using the "Run" command

### ISSUE THREAD

**Issue by amahlaka** [demisto/demisto-sdk#2030]
When using demisto-sdk with a multi-tenant xsoar server, it would be good to be able to set the "target" tenant  as a parameter in the command, instead of having to change it in the enviroment/config
for example: demisto-sdk run -q "Print test" --account=acc_tenant1

P.S:
If you just change the server address to include "/acc_tenant", API keys created in main account dont work properly, and authentication fails

**Comment by dorschw** [comment]
Hi again, this feature is not prioritized at the moment. 
If you're an XSOAR/XSIAM customer, please open a request on Aha!, or contact XSOAR Customer Success.
