### ISSUE TITLE
demisto-sdk 1.6.4 upload fails to XSOAR 6

### ISSUE THREAD

**Issue by davidt99** [demisto/demisto-sdk#2052]
I uploaded an integration with sdk version 1.6.4 to a server version 6.0.2.
When running any command, I'm getting:
```
Error from <integration-name> is : Script failed to run:
Error: [Traceback (most recent call last):
   
   File "<string>", line 1, in <module>
 NameError: name 'register_module_line' is not defined
] (2604) (2603)
```
I downgraded to 1.4.9 and that solve the issue.

**Comment by dorschw** [comment]
Hi David,
What version of the `Base` pack are you using?

Please update it to `1.18.0` or newer, and let us know whether the issue persists.
If updating `Base` is not possible, SDK versions up to 1.5.5 (inclusive) should work, as they don't include this feature (which enables easy debugging of content items).

We recommend using the latest versions of both `Base` and the demisto-sdk, as newer versions bring performance improvements and bug fixes.

**Comment by dorschw** [comment]
If the issue persists after upgrading the `Base` pack post 1.18.0, please reopen this issue with details

**Comment by davidt99** [comment]
@dorschw I've upgraded Base to `1.30.10`, now I'm getting:
```
Error from <integration name> is : Script failed to run: 
Error: [Traceback (most recent call last):
   
   File "<string>", line 21, in <module>
 ModuleNotFoundError: No module named 'Packs'
] (2604) (2603)
```
Any thing you can help?

**Comment by dorschw** [comment]
Yes, please attach the full command you're running, and the folder from which you call it (pwd). 
Instincts say the path passed in `-i` may be incorrect.

**Comment by davidt99** [comment]
Actually, It was my mistake with the imports, it works fine with the latest demisto-sdk and Base package.
