### ISSUE TITLE
Pack README is checked for relative image path, prints RM108

### ISSUE THREAD

**Issue by kgal-pan** [demisto/demisto-sdk#2173]
https://github.com/demisto/demisto-sdk/blob/24ff82034690c98be15f115484600ba195d1c73d/demisto_sdk/commands/common/hook_validations/readme.py#L278

**Comment by dorschw** [comment]
@kgal-pan, please see [here](https://panw-global.slack.com/archives/C01A4L1UW56/p1655282716885239?thread_ts=1655282391.077709&cid=C01A4L1UW56)
