### ISSUE TITLE
Inconsistent whitespace formatting

### ISSUE THREAD

**Issue by icholy** [demisto/demisto-sdk#2206]
The merging functionality appears to change indentation in the yaml & json files from tabs to spaces.

### What did you do?

1. Downloaded all of my custom content to a private repo.

``` sh
$ demisto-sdk download -a -o ./Packs/MyStuff
```

2. Ran the command again with the `--force` flag.

```
$ demisto-sdk download -a -f -o ./Packs/MyStuff
```

### What did you expect to happen?

The second command would not change any local files.

### What happened instead?

The indentation whitespace changed from tabs to spaces.

**Comment by dorschw** [comment]
Hi ilia, thanks for opening an issue, we'll have a look. Which version of
the SDK are you using? The version is printed every time a command is
called. Alternatively, you can run demisto-sdk --version.

**Comment by dorschw** [comment]
Thanks, this will be tracked internally as [CIAC-3400](https://github.com/demisto/demisto-sdk/issues/2206).
We'll update here once there's news.
