### ISSUE TITLE
Quotation marks in query causing crash with "XSOAR: Run a command in XSOAR"

### ISSUE THREAD

**Issue by ichhabkeinbock** [demisto/demisto-sdk#2234]
**Expected behaviour:**
```
CTRL+SHIFT+P > XSOAR: Run a command in XSOAR > !vscode_test dummy="this is a test"
Open new console and executes the following command:
$ C:\Users\USER\AppData\Local\Programs\Python\Python310\Scripts\demisto-sdk.exe run -q '!vscode_test dummy="test"'
### Command:
## Readable Output
### Results
|dummy|
|---|
| 'this is a test' |
```

**Actual behaviour:**
```
CTRL+SHIFT+P > XSOAR: Run a command in XSOAR > !vscode_test dummy="this is a test"
Open new console and executes the following command:
$ C:\Users\J46313\AppData\Local\Programs\Python\Python310\Scripts\demisto-sdk.exe run -q "!vscode_test dummy=\"this is a test\""
## Readable Output
!vscode_test dummy=" this is a test\

### Command:
## Readable Output
unterminated quoted string (6)
```
But quotation marks are needed when using argument values containing spaces.

**Steps to reproduce:**
- create dummy playbook: `demisto-sdk.exe init --script --id "vscode_test" -n VScodeTest`
- upload dummy playbook to your XSOAR instance
- do the step described in "Expected/Actual behaviour"

**System**
- demisto-sdk==1.6.7 (as 1.6.9 cannot be installed, see #2233)
- Windows 11 - 10.0.22000 Build 22000
- Python 3.10

**Comment by dorschw** [comment]
Windows machines are not supported by the SDK, see #2233 for more information and the alternatives (WSL/Docker)
