### ISSUE TITLE
demisto-sdk download/Upload - Support XSIAM Content features

### ISSUE THREAD

**Issue by adambaumeister** [demisto/demisto-sdk#2266]
To support authoring and scaling content development for XSIAM, we need the demisto-sdk download and upload functionality to support the following additional file types;

**Must-Haves**
 * Data-model rules
 * Parsing Rules
 * XSIAM Dashboards and Reports
 * Correlation Rule - *How do we actually export these, is it possible via the API?*

**Nice-to-have**
 * Triggers - *This is probably customer-specific so is only a nice-to-have*
 * Scoring Rules - *Same as above*

@DinaMeylakh @bakatzir

**Comment by yaakovi** [comment]
There isn't an API to perform those actions at the moment. (should be added in future versions of XSIAM).
you can use the `demisto-sdk upload -z -x` command to upload an entire pack with XSIAM items.

**Comment by ShahafBenYakir** [comment]
Closing as we already have internal issues to add these which are currently blocked due to the reason mentioned above.
