### ISSUE TITLE
demisto-sdk generate-unit-tests not giving expected results

### ISSUE THREAD

**Issue by johnnywilkes** [demisto/demisto-sdk#2343]
I believe I meet the required code conventions but I am not getting what I would like from the 'demisto-sdk generate-unit-tests' command and also not getting an errror:

`(.venv) jwilkes@M-WFMVK7QJWV CortexAttackSurfaceManagement % demisto-sdk generate-unit-tests -d -v -a --insecure -e /Users/jwilkes/Code/content-JW-Fork/Packs/CortexAttackSurfaceManagement/Integrations/CortexAttackSurfaceManagement/command_examples -i /Users/jwilkes/Code/content-JW-Fork/Packs/CortexAttackSurfaceManagement/Integrations/CortexAttackSurfaceManagement/CortexAttackSurfaceManagement.py
You are using demisto-sdk 1.7.4.
================= Running Unit Testing Generator ===================
found the following commands:
!asm-getassetinternetexposure asm_id=8f48d3e8-306a-11ed-a261-0242ac120002
!asm-getexternalipaddressrange range_id=8f48d3e8-306a-11ed-a261-0242ac120002
!asm-getexternalservice service_id=8f48d3e8-306a-11ed-a261-0242ac120002
!asm-getexternalipaddressranges
!asm-getassetsinternetexposure name="testdomain.com" type=certificate has_active_external_services=no
!asm-getexternalservices domain=testdomain.com is_active=yes discovery_type=directly_discovery
Unit tests will be generated for the following commands:
asm_getassetinternetexposure_command
asm_getexternalipaddressrange_command
asm_getexternalservice_command
asm_getexternalipaddressranges_command
asm_getassetsinternetexposure_command
asm_getexternalservices_command
Successfully finished generating integration code and saved it in /Users/jwilkes/Code/content-JW-Fork/Packs/CortexAttackSurfaceManagement/Integrations/CortexAttackSurfaceManagement`

**Comment by johnnywilkes** [comment]
```
(.venv) jwilkes@M-WFMVK7QJWV CortexAttackSurfaceManagement % demisto-sdk generate-unit-tests -d -v -a --insecure -e /Users/jwilkes/Code/content-JW-Fork/Packs/CortexAttackSurfaceManagement/Integrations/CortexAttackSurfaceManagement/command_examples -i /Users/jwilkes/Code/content-JW-Fork/Packs/CortexAttackSurfaceManagement/Integrations/CortexAttackSurfaceManagement/CortexAttackSurfaceManagement.py You are using demisto-sdk 1.7.4. ================= Running Unit Testing Generator =================== found the following commands: !asm-getassetinternetexposure asm_id=8f48d3e8-306a-11ed-a261-0242ac120002 !asm-getexternalipaddressrange range_id=8f48d3e8-306a-11ed-a261-0242ac120002 !asm-getexternalservice service_id=8f48d3e8-306a-11ed-a261-0242ac120002 !asm-getexternalipaddressranges !asm-getassetsinternetexposure name="testdomain.com" type=certificate has_active_external_services=no !asm-getexternalservices domain=testdomain.com is_active=yes discovery_type=directly_discovery Unit tests will be generated for the following commands: asm_getassetinternetexposure_command asm_getexternalipaddressrange_command asm_getexternalservice_command asm_getexternalipaddressranges_command asm_getassetsinternetexposure_command asm_getexternalservices_command Successfully finished generating integration code and saved it in /Users/jwilkes/Code/content-JW-Fork/Packs/CortexAttackSurfaceManagement/Integrations/CortexAttackSurfaceManagement
```

**Comment by johnnywilkes** [comment]
[Archive.zip](https://github.com/demisto/demisto-sdk/files/9537868/Archive.zip)
Here is my integration code, example commands and the outputed unit tests file

**Comment by eyalpalo** [comment]
Hi @johnnywilkes, 
After debugging the process it seems that the problem lays in the fact that the name of the commands (the function itself) does not start with the vendor name, for instance when the SDK expect ```asm_getexternalservice_command``` it cannot find it, because the name of the function is ```getexternalservice_command```.

This is not part of the required conventions as stated in the command readme, and will be fixed in the next SDK release in order to give the user the option to name the functions of the command as you did.

For now, until the next release, you can just add ```asm_``` prefix in every command function and the command will generate unit tests. 

Also, pay attention that because you return a var that contain a CommandResults object and not a CommandResults object directly no asserts will be generated (also will be considered to be fixed in next release). To fix that simply return the CommandResults object itself (e.g. 

```
 return CommandResults(
        outputs_prefix='test',
        outputs_key_field='test',
        outputs=parsed,
        raw_response=parsed,
        readable_output=markdown
    )
```
