### ISSUE TITLE
Upload command overwrites content silently

### ISSUE THREAD

**Issue by K-Yo** [demisto/demisto-sdk#2349]
when using `demisto-sdk upload` command, some content can be overwritten without user being informed.

this happens (for example) when you upload a pack with an integration having the same name as an integration already existing on XSOAR.

**Comment by dorschw** [comment]
Hey @K-Yo, thanks for opening an issue

The ID field is designed to be unique, e.g. non two integrations should use the same value as their ID.

This is automatically validated when using the id-set (see the `create id-set` command), as part of the recommended content CI/CD flow.
