### ISSUE TITLE
Semantic Versioning and Releases

### ISSUE THREAD

**Issue by mattbibbydw** [demisto/demisto-sdk#2397]
This project appears to be following the Semantic Versioning (MAJOR.MINOR.PATCH) format, but not following the [SemVer Specifications](https://semver.org/#semantic-versioning-specification-semver). 

Currently all changes are merged into master branch a released on a bi-weekly basis as a PATCH release (incrementing the `Z`).  If the PATCH number is 9, the MINOR number is incremented and the PATCH number is set to 0. The issue with this strategy is it reduces the value of the version number to nothing more than a counter. 

Per the SemVer spec:
> Given a version number MAJOR.MINOR.PATCH, increment the:
> 
> 1. MAJOR version when you make incompatible API changes
> 2. MINOR version when you add functionality in a backwards compatible manner
> 3. PATCH version when you make backwards compatible bug fixes
> Additional labels for pre-release and build metadata are available as extensions to the MAJOR.MINOR.PATCH format.

_(source: [semver.org](https://semver.org/#summary))_

Adopting the entire spec might seem a bit daunting, but this project would greatly benefit from following a two key principles:

1. **Allow MINOR/PATCH versions to increment beyond 9.** This would go a long way in improving how changes are communicated and would be fairly easy to implement. Just stay on the current `MAJOR.MINOR` version and keep incrementing the PATCH until additional release management processes are adopted.
2. **Create a separate branch for PATCH changes that gets released regularly.** An example of how this can be achieved can be seen in projects like [click](https://github.com/pallets/click). Their [Contributing](https://github.com/pallets/click/blob/main/CONTRIBUTING.rst) docs are especially helpful.

**Comment by dorschw** [comment]
Hi, thanks for the suggestion, I agree that minor versions should have
greater meaning.

It's a holiday season here, we'll address it in a couple of weeks and
update here.
