### ISSUE TITLE
Add custom headers?

### ISSUE THREAD

**Issue by fancybear-dev** [demisto/demisto-sdk#2452]
It is not a bug, but a question / feature request.

Is it possible to add custom headers to all requests easily?

We have xsoar servers that are behind a proxy - that works just fine, except that the demisto-sdk (which uses the demisto-py client) does not support custom headers. We need an additional header to pass through the proxy. Is this possible? If not, any suggestions on a quick fix?

I've created this issue at the client level as well; https://github.com/demisto/demisto-py/issues/103

**Comment by dorschw** [comment]
https://github.com/demisto/demisto-py/issues/103#issuecomment-1308637606

**Comment by dorschw** [comment]
see closing comment in the linked demisto-py
