### ISSUE TITLE
Download unnecessarily creates temporary directory with requirements.txt

### ISSUE THREAD

**Issue by maxgubler** [demisto/demisto-sdk#2487]
After #2364 (@JudahSchwartz), running download now creates a temporary directory containing `requirements.txt`. This is unnecessary and makes the download process slower.

### How / why this happening

Unrelated imports leading to an unnecessary instantiation of `Docker` (within `docker_helper.py`).

#### Here's the import flow causing this

1) <https://github.com/demisto/demisto-sdk/blob/fde9ba416c16611304dbdd5f45f069c5234b942d/demisto_sdk/commands/download/downloader.py#L36>
2) <https://github.com/demisto/demisto-sdk/blob/fde9ba416c16611304dbdd5f45f069c5234b942d/demisto_sdk/commands/format/format_module.py#L15-L16>
3) <https://github.com/demisto/demisto-sdk/blob/fde9ba416c16611304dbdd5f45f069c5234b942d/demisto_sdk/commands/format/update_classifier.py#L11>
4) <https://github.com/demisto/demisto-sdk/blob/fde9ba416c16611304dbdd5f45f069c5234b942d/demisto_sdk/commands/format/update_generic_json.py#L12>
5) <https://github.com/demisto/demisto-sdk/blob/fde9ba416c16611304dbdd5f45f069c5234b942d/demisto_sdk/commands/format/update_generic.py#L19>
6) <https://github.com/demisto/demisto-sdk/blob/fde9ba416c16611304dbdd5f45f069c5234b942d/demisto_sdk/commands/validate/validate_manager.py#L72-L73>
7) <https://github.com/demisto/demisto-sdk/blob/fde9ba416c16611304dbdd5f45f069c5234b942d/demisto_sdk/commands/common/hook_validations/pack_unique_files.py#L36>
8) <https://github.com/demisto/demisto-sdk/blob/fde9ba416c16611304dbdd5f45f069c5234b942d/demisto_sdk/commands/common/hook_validations/readme.py#L21>
9) <https://github.com/demisto/demisto-sdk/blob/fde9ba416c16611304dbdd5f45f069c5234b942d/demisto_sdk/commands/common/docker_helper.py#L207>
10) <https://github.com/demisto/demisto-sdk/blob/fde9ba416c16611304dbdd5f45f069c5234b942d/demisto_sdk/commands/common/docker_helper.py#L63-L80>

---

### Two suggestions I have here

1) **Potential simplest solution**: Instantiate `Docker` at the time when the `__init__` is _actually_ needed:
    <https://github.com/demisto/demisto-sdk/blob/fde9ba416c16611304dbdd5f45f069c5234b942d/demisto_sdk/commands/lint/linter.py#L682-L683>
    Correct me if I'm wrong (@JudahSchwartz / @esharf), but this appears to be the _only_ place where the code within `__init__` is needed. Having it instantiated at the end of `docker_helper.py` causes this problem when trying to import anything else from it (**Note: There are quite a few more places where `init_global_docker_client` is imported, so this issue should affect more than just download**).
    Referencing @esharf: <https://github.com/demisto/demisto-sdk/pull/1982#discussion_r841208920>
2) Move the `__init__` code back into the `create_image` method (which was changed in  #1982). To me, the result of `__init__` for a class should be generally useful for multiple methods. That doesn't seem to be the case here. If `MountableDocker` needs to implement `create_image` differently, it should have its own definition.

**Bonus suggestions:**

* Rename `Docker` to `DockerHelper` (or really... anything else 😑)

* Revert to using `with tempfile.TemporaryDirectory...`:

    This original code:
    <https://github.com/demisto/demisto-sdk/blob/00eeaa92a9387a7a0ffa96b1184fdf3b0225fcc7/demisto_sdk/commands/lint/docker_helper.py#L134>
    cleans up better than:
    <https://github.com/demisto/demisto-sdk/blob/820bfc518877a7a214a9a416e838572c30357140/demisto_sdk/commands/lint/docker_helper.py#L53>...
    <https://github.com/demisto/demisto-sdk/blob/820bfc518877a7a214a9a416e838572c30357140/demisto_sdk/commands/lint/docker_helper.py#L70-L71>
    ^ That's how I noticed this temp file creation bug in the first place. It was leaving behind temp directories / failing to clean up nicely.

**Comment by JudahSchwartz** [comment]
@maxgubler awesome catch, thanks! 
And thanks for the detailed explanation and the solution
I'll open a pr shortly to fix the main issue. 

Please feel free to make contributions to this repo, regarding this time or in the future! You can find our contributions guideline [here](https://github.com/demisto/demisto-sdk/blob/master/CONTRIBUTION.md)
