### ISSUE TITLE
Missing CommonServerPython & demisto_mock files in new integration

### ISSUE THREAD

**Issue by PakitoSec** [demisto/demisto-sdk#2496]
Hello,

Using the command below doesn't copy files CommonServerPython & demisto_mock.
Also the  DemistoClassApiModule.py is not copied in the integration folder so there is a bug when the integration script is executed locally...

Could you please indicate the right process in order to have all necessary files needed in an integration folder for a local execution in order to test & debug ?

```
demisto-sdk init --integration -n MyNewIntegration -o path/to/my/dir --demisto_mock --common-server
```

For information, my usecase is in an external content folder as described in your github.

Thank you,

**Comment by dorschw** [comment]
Hi @PakitoSec, running `demisto-sdk lint -i <path to integration yml>` should copy all necessary files to run locally.

Alternatively (and sometimes better), we recommend using Visual Studio Code with the [XSOAR extension](https://marketplace.visualstudio.com/items?itemName=CortexXSOARext.xsoar). Configuring a virtual environment (right click anywhere in VSCode, it's one of the last options) should allow running and debugging code content.

Feel free to reopen this issue if the issue persists.

**Comment by PakitoSec** [comment]
Thank you for your feedback, but with `demisto-sdk lint -i`, there is still a missing file which is `DemistoClassApiModule.py`
