### ISSUE TITLE
Your mapper contains incident fields that do not exist in the content: ['Event Type', 'File MD5', 'File Name', 'File SHA256', 'Event Type'].

### ISSUE THREAD

**Issue by ennozdd** [demisto/demisto-sdk#2674]
```
$ gsutil cp gs://marketplace-dist/content/id_set.json Tests/content-id_set.json
$ demisto-sdk create-id-set
$ demisto-sdk merge-id-sets -i1 Tests/id_set.json -i2 Tests/content-id_set.json -o Tests/id_set.json
$ demisto-sdk validate --quiet-bc-validation --no-conf-json --allow-skipped --skip-pack-release-notes
[ERROR]: Packs/MyPack/Classifiers/classifier-My_Mapper.json: [MP106] - Your mapper contains incident fields that do not exist in the content: ['Event Type', 'File MD5', 'File Name', 'File SHA256', 'Event Type'].
Please make sure:
1 - The right incident field is set and the spelling is correct.
2 - The id_set.json file is up to date. Delete the file by running: rm -rf Tests/id_set.json and rerun the command.
```

**Comment by ennozdd** [comment]
https://github.com/demisto/content/blob/master/Packs/CommonTypes/IncidentFields/incidentfield-Event_Type.json
https://github.com/demisto/content/blob/master/Packs/CommonTypes/IncidentFields/incidentfield-File_MD5.json
https://github.com/demisto/content/blob/master/Packs/CommonTypes/IncidentFields/incidentfield-File_Name.json
https://github.com/demisto/content/blob/master/Packs/CommonTypes/IncidentFields/incidentfield-File_SHA256.json

My understanding is that they exist in the content but not in id_set

**Comment by ilaner** [comment]
Can you upload your custom mapper?

**Comment by ennozdd** [comment]
![image](https://user-images.githubusercontent.com/49711791/213147821-ba25f763-0660-4dad-b838-64227374f924.png)


@ilaner I may be totally wrong here but when I look at the id_set.json from gs://marketplace-dist/content/id_set.json 
event type for example is not listed as an incident field. 


![image](https://user-images.githubusercontent.com/49711791/213185841-09526255-6678-4319-ab1e-6595870ce43f.png)
running demisto-sdk create-id-set on demisto/content however gives it as a field

is id_set.json at gs://marketplace-dist/content/id_set.json obsolete?
