### ISSUE TITLE
demisto-sdk doc-review command showing unexpected unknown words.

### ISSUE THREAD

**Issue by nofiyabanugandhi-crest** [demisto/demisto-sdk#2800]
The demisto-sdk doc-review command returns an unknown word error for a few known words also, such as ```History.isAvailable```.

We discovered that the function [camel case split](https://github.com/demisto/demisto-sdk/blob/master/demisto_sdk/commands/doc_reviewer/doc_reviewer.py#L175) is not functioning as expected after debugging this issue.

```
def camel_case_split(camel):
        """split camel case word into sub-words"""
        tokens = re.compile("([A-Z]?[a-z]+)").findall(camel)
        for token in tokens:
            # double space to handle capital words like IP/URL/DNS that not included in the regex
            camel = camel.replace(token, f" {token} ")

        return camel.split()
```

```re.compile("([A-Z]?[a-z]+)").findall(camel)``` >> The camel case word is divided into list of words. which is ['History', 'is', 'Available'].

The following stage involves inserting spaces before and after each word in the loop.
```
for token in tokens:
     # double space to handle capital words like IP/URL/DNS that not included in the regex
      camel = camel.replace(token, f" {token} ")
```

We observed that, for the above example, it is creating a string as ``` H is tory . is  Available ```.  Because it adds whitespace twice for the "is" keyword, the word "history" is divided and recorded as an unknown word.

**Comment by kgal-pan** [comment]
Hi @nofiyabanugandhi-crest - When checking this regex with the supplied string, it generates 3 words as expected:

```python
>>> import re
>>> re.compile("([A-Z]?[a-z]+)").findall("History.isAvailable")
['History', 'is', 'Available']
```
