### ISSUE TITLE
Lint failing when attempting to wait for container to exit

### ISSUE THREAD

**Issue by rajatdoshi1druva** [demisto/demisto-sdk#2833]
Attempting to use the `lint` command results in an exception from the Docker container API:

```
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: http+docker://localhost/v1.42/containers/36e11de0f0cbe93dd9319cc4af9a8be8b0bec0240d9604997c1f09403dcf350b/wait?condition=exited
```

Reviewing the [SDK code](https://github.com/demisto/demisto-sdk/blob/master/demisto_sdk/commands/lint/linter.py#L1019), it seems that we're polling the container API to wait for the `exited` state:
```python
container.wait(condition="exited")
```

According to [the Docker SDK docs](https://docker-py.readthedocs.io/en/stable/containers.html#docker.models.containers.Container.wait), the exited option is not supported:

> wait(**kwargs)
> Block until the container stops, then return its exit code. Similar to the docker wait command.
> ...
> Parameters
> condition (str) – Wait until a container state reaches the given condition, **either not-running (default), next-exit, or removed**

[lint.log](https://github.com/demisto/demisto-sdk/files/10956324/lint.log)

This was looked and found by @kgal-pan by looking at the attached logs.

docker version information as below:
```
ubuntu@ubuntu:~$ docker version
Client: Docker Engine - Community
 Version:           23.0.1
 API version:       1.42
 Go version:        go1.19.5
 Git commit:        a5ee5b1
 Built:             Thu Feb  9 19:47:01 2023
 OS/Arch:           linux/amd64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          23.0.1
  API version:      1.42 (minimum version 1.12)
  Go version:       go1.19.5
  Git commit:       bc3805a
  Built:            Thu Feb  9 19:47:01 2023
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.16
  GitCommit:        31aa4358a36870b21a992d3ad2bef29e1d693bec
 runc:
  Version:          1.1.4
  GitCommit:        v1.1.4-0-g5fd4c4d
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

```

**Comment by rajatdoshi1druva** [comment]
docker version information:

```
ubuntu@ubuntu:~$ docker version
Client: Docker Engine - Community
 Version:           23.0.1
 API version:       1.42
 Go version:        go1.19.5
 Git commit:        a5ee5b1
 Built:             Thu Feb  9 19:47:01 2023
 OS/Arch:           linux/amd64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          23.0.1
  API version:      1.42 (minimum version 1.12)
  Go version:       go1.19.5
  Git commit:       bc3805a
  Built:            Thu Feb  9 19:47:01 2023
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.16
  GitCommit:        31aa4358a36870b21a992d3ad2bef29e1d693bec
 runc:
  Version:          1.1.4
  GitCommit:        v1.1.4-0-g5fd4c4d
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

```

**Comment by crestdatasystems** [comment]
We are also facing same issue while running linting.
docker version information as below:

`
Client: Docker Engine - Community
 Version:           23.0.1
 API version:       1.42
 Go version:        go1.19.5
 Git commit:        a5ee5b1
 Built:             Thu Feb  9 19:51:00 2023
 OS/Arch:           linux/amd64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          23.0.1
  API version:      1.42 (minimum version 1.12)
  Go version:       go1.19.5
  Git commit:       bc3805a
  Built:            Thu Feb  9 19:48:42 2023
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.18
  GitCommit:        2456e983eb9e37e47538f59ea18f2043c9a73640
 runc:
  Version:          1.1.4
  GitCommit:        v1.1.4-0-g5fd4c4d
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
`

**Comment by dorschw** [comment]
Thank you, this is handled internally as [CIAC-6070](https://jira-hq.paloaltonetworks.local/browse/CIAC-6070)
