### ISSUE TITLE
Download List Files Produces No Output

### ISSUE THREAD

**Issue by tbailey25** [demisto/demisto-sdk#2853]
Should the output of `demisto-sdk download --list-files` go to the logger or be output for the user? Running the command from version 1.11.0 does not result in the expected output. Looks like there was a recent [commit](https://github.com/demisto/demisto-sdk/commit/81bc997097acd1ea360ef481e78e83c9a89f0cfd) that switched the print statements to logger statements, [here](https://github.com/demisto/demisto-sdk/blob/master/demisto_sdk/commands/download/downloader.py#L564).

This is the only output.
```
$ demisto-sdk download --list-files --insecure
You are using demisto-sdk 1.11.0.
```

**Comment by dorschw** [comment]
Thanks, this was a bug, solved by https://github.com/demisto/demisto-sdk/pull/2850.
