### ISSUE TITLE
demisto-sdk run_cmd default size limitation on playground API causing an error when trying to execute a query

### ISSUE THREAD

**Issue by vicmar987** [demisto/demisto-sdk#2885]
Hello all,

We are using the demisto-sdk to run integration commands from our CI CD tool. We have a MSSP setup where an admin account created the API key on the Main account and has it setup automatically on all our tenants. Using this API with demisto-sdk causes an error due to the following:
in demisto_sdk/commands/run_cmd/runner.py --> _get_playground_id. The playground filter only looks at type 9 (playground). However this API only returns 25 results even if there are more than 25. Our Admin playground is number 36 and will cause an error that no play ground is found.

Adding the following "size" parameter fixes the bug: playground_filter = {'filter': {'type': [9], 'size': 200}}.

Is it possible to add this size parameter to the playground_filter? A first API call could be used to get the total records and afterwards used in the 'size' parameter to always have the correct parameter.

Thanks!

**Comment by dorschw** [comment]
Hi, thank you, this is tracked internally as [XSUP-23185](https://jira-hq.paloaltonetworks.local/browse/XSUP-23185)
