### ISSUE TITLE
Ignored errors not removed from output when running validate -j

### ISSUE THREAD

**Issue by K-Yo** [demisto/demisto-sdk#2948]
When using `-j` flag with the `validate` command and ignoring some errors in the `.pack-ignore` file, the errors are ignored in the standard output, but they are still shown in the json export.

There isn’t any specific field in the json export showing if an error has been ignored or not, which makes automated processing of errors very difficult.

**Comment by dorschw** [comment]
Hi, thanks for opening an issue. 
Please contact Cortex support and ask them to add your customer details to jira ticket XSUP-23805.

**Comment by dorschw** [comment]
Please contact Paloalto Networks support to continue the handling of this ticket.
