### ISSUE TITLE
Pre-Commit condition for staged files needs to be referenced first

### ISSUE THREAD

**Issue by shaqnawe** [demisto/demisto-sdk#2985]
The following line

https://github.com/demisto/demisto-sdk/blob/ee04498cc334ad8b5deb66f4fd8f0ab340a27ad7/demisto_sdk/commands/pre_commit/pre_commit_command.py#L291

may need to be changed to 

``` python   
elif use_git:
        raw_files = staged_files | git_util._get_all_changed_files()
```

because otherwise, staged files will not be prioritized first, causing a full scan on all content packs relative to the main branch.

**Comment by dorschw** [comment]
Hi @shaqnawe, thanks for opening an issue! We plan a `--staged-only` flag to run on staged files only soon.

(Currently, the result is an unordered set, there's no prioritization of files - `git_util._get_all_changed_files()` is always called, so changing the order will not affect the result.)
