### ISSUE TITLE
Unable to uninstall (and reinstall) demisto-sdk

### ISSUE THREAD

**Issue by ariel-wiz** [demisto/demisto-sdk#3201]
I have some issues with demisto-sdk, then I would like to uninstall it, then reinstall but it doesn't seem it is uninstalled
**Installation**
`Successfully installed demisto-py-3.2.10 demisto-sdk-1.17.0
(base) ariel@Ariels-MacBook-Pro-2 ~ % demisto-sdk --version   
Please run demisto-sdk in content repository!
Please run demisto-sdk in content repository!
Please run demisto-sdk in content repository!
Please run demisto-sdk in content repository!
Please run demisto-sdk in content repository!
Please run demisto-sdk in content repository!
You are using demisto-sdk 1.8.1.
however version 1.17.0 is available.
To update, run pip3 install --upgrade demisto-sdk
`

**Version**
`(base) ariel@Ariels-MacBook-Pro-2 ~ % demisto-sdk --version   
Please run demisto-sdk in content repository!
Please run demisto-sdk in content repository!
Please run demisto-sdk in content repository!
Please run demisto-sdk in content repository!
Please run demisto-sdk in content repository!
Please run demisto-sdk in content repository!
You are using demisto-sdk 1.8.1.
however version 1.17.0 is available.
To update, run pip3 install --upgrade demisto-sdk
`

**Upgrade**
`pip3 install --upgrade demisto-sdk
....
Installing collected packages: demisto-sdk
Successfully installed demisto-sdk-1.17.0
`

Version
`(base) ariel@Ariels-MacBook-Pro-2 ~ % demisto-sdk --version   
Please run demisto-sdk in content repository!
Please run demisto-sdk in content repository!
Please run demisto-sdk in content repository!
Please run demisto-sdk in content repository!
Please run demisto-sdk in content repository!
Please run demisto-sdk in content repository!
You are using demisto-sdk 1.8.1.
however version 1.17.0 is available.
To update, run pip3 install --upgrade demisto-sdk
`

**Uninstall**
`(base) ariel@Ariels-MacBook-Pro-2 ~ % pip3 uninstall demisto-sdk
Found existing installation: demisto-sdk 1.17.0
Uninstalling demisto-sdk-1.17.0:
  Would remove:
    /Users/ariel/opt/anaconda3/bin/demisto-sdk
    /Users/ariel/opt/anaconda3/lib/python3.9/site-packages/demisto_sdk-1.17.0.dist-info/*
    /Users/ariel/opt/anaconda3/lib/python3.9/site-packages/demisto_sdk/*
Proceed (Y/n)? Y
  Successfully uninstalled demisto-sdk-1.17.0
`

`(base) ariel@Ariels-MacBook-Pro-2 ~ % pip uninstall demisto-sdk
WARNING: Skipping demisto-sdk as it is not installed.
(base) ariel@Ariels-MacBook-Pro-2 ~ % pip3 uninstall demisto-sdk
WARNING: Skipping demisto-sdk as it is not installed.
`

**Version**
`(base) ariel@Ariels-MacBook-Pro-2 ~ % demisto-sdk --version   
Please run demisto-sdk in content repository!
Please run demisto-sdk in content repository!
Please run demisto-sdk in content repository!
Please run demisto-sdk in content repository!
Please run demisto-sdk in content repository!
Please run demisto-sdk in content repository!
You are using demisto-sdk 1.8.1.
however version 1.17.0 is available.
To update, run pip3 install --upgrade demisto-sdk
`

Please advise

**Comment by kgal-pan** [comment]
Issue resolved by uninstalling and reinstalling the SDK in the `content` repo using:

```bash
.hooks/bootstrap
```
