### ISSUE TITLE
demisto-sdk download doesn't log where it downloaded

### ISSUE THREAD

**Issue by ennozdd** [demisto/demisto-sdk#3216]
```
$ demisto-sdk download -i 'Incident Metrics' -o Packs/TEST-f

Demisto instance: Enumerating objects: 1, done.
Demisto instance: Receiving objects: 100% (1/1), done.
- Merged Dashboard "Incident Metrics"
1 file merged.
```

This is important for dashboards where demisto-sdk fails to download with the correct ID so demisto-sdk format needs to be run on the file. It takes me a few seconds to remember the location every time I download something.

demisto-sdk should log the full path of the downloaded file.

**Comment by dorschw** [comment]
Hey, thanks for opening an issue. Please raise this as a feature request via [Aha](https://xsoar.ideas.aha.io/ideas) so that we can prioritize it.
