### ISSUE TITLE
Packs uploaded with demisto-sdk aren't displayed properly in Pack Details

### ISSUE THREAD

**Issue by ennozdd** [demisto/demisto-sdk#3242]
Installed via the marketplace
![image](https://github.com/demisto/demisto-sdk/assets/49711791/13f46d58-e6a7-4b21-95ec-66bbc7c9be31)

Installed via demisto-sdk upload -i $PACK -z
![image](https://github.com/demisto/demisto-sdk/assets/49711791/577df8d1-df28-473a-8415-429c049455d1)

[INFO] You are using demisto-sdk 1.17.1.

**Comment by dorschw** [comment]
Thank you, this is tracked internally as [XSUP-25968](https://jira-hq.paloaltonetworks.local/browse/XSUP-25968)

**Comment by ennozdd** [comment]
https://github.com/demisto/demisto-sdk/pull/3266

The issue seems to be resolved
