### ISSUE TITLE
demisto-sdk "format" is removing incident fields from a custom layout 

### ISSUE THREAD

**Issue by ennozdd** [demisto/demisto-sdk#3471]
![image](https://github.com/demisto/demisto-sdk/assets/49711791/69eb882b-7633-4c17-9a2a-e4395783f825)

in a private repository running demisto-sdk format is removing many fields from a modified layout.
The fields that are being extracted are not new to the layout they have been always there but latest demisto-sdk wants to remove them.
upgraded from v1.17.2 to v1.19.0

**Comment by ennozdd** [comment]
[demisto_debug.log](https://github.com/demisto/demisto-sdk/files/12357684/demisto_debug.log)

**Comment by sapirshuker** [comment]
Hey, we made some changes to the SDK. The format command now runs with a new implementation. In order to avoid this issue, please use the command with the '-ngr' or '--no-graph' flag.
Please let me know if this solution works for you.

**Comment by kgal-pan** [comment]
Likely related to changes made in https://github.com/demisto/demisto-sdk/pull/3389.

**Comment by kgal-pan** [comment]
@ennozdd - Do you have:

1) The https://github.com/demisto/content repo locally cloned locally in your environment?
2) Have you set `DEMISTO_SDK_CONTENT_PATH` (see https://github.com/demisto/demisto-sdk#content-path)? If so, to what directory?

**Comment by kgal-pan** [comment]
@sapirshuker - This issue was fixed n https://github.com/demisto/demisto-sdk/pull/3580
