### ISSUE TITLE
Download UUID to Name changes break file on upload

### ISSUE THREAD

**Issue by maxgubler** [demisto/demisto-sdk#3518]
When downloading a [PLAYBOOK, AUTOMATION, INTEGRATION, LAYOUT, INCIDENT](https://github.com/demisto/demisto-sdk/blob/2c4ac7b0ce4195becc3bf1b6700dd385a2a0998f/demisto_sdk/commands/download/downloader.py#L381) the downloaded file is intentionally mangled (UUID->Name) to the point where uploading it breaks functionality or it fails to upload at all (XSOAR v6.11.0).

Example (Broken upload):
1. Download a layout.
2. The layout "id", which is a UUID on the server, is changed to the name of the layout.
3. Attempt to upload this file with demisto-sdk.
4. The upload fails with the error that a layout already exists (because it's trying to create a new layout [because the "id" (which is actually the name) is new] and yet the name of that layout already exists).

Example (Broken functionality):
1. Download a layout which has a button that runs a script.
2. The layout "id" is changed as above, and the button "scriptId" is changed to the script's name.
3. The "scriptId" for the button is changed to the name of the script.
4. If you attempt to upload, it'll fail as above.
5. Change the layout "id" back to its UUID.
6. Upload the file and it'll "succeed"
7. The button will not work or not show because its "scriptId" doesn't exist.

This appears to have started with:
#2572 / 0bdf53c - Custom Scripts in IncidentFields and Layouts
and is now affecting more content types after these:
#2639 / 52baa50 - Fix UUID in playbook regression
#2934 / c5efcef - Add layout type files to the map uuid to names

What kind of workflow are you all using where this hasn't been a problem?

**Comment by dorschw** [comment]
Hi @maxgubler, thanks for opening an issue. It is tracked internally as [XSUP-27596](https://jira-hq.paloaltonetworks.local/browse/XSUP-27596).

Please contact PANW support and ask them to fill the customer information in that issue, so that we can prioritize it accordingly.

**Comment by maxgubler** [comment]
Done; however, I'd rather contribute a solution here and get this resolved. But, I need help understanding:

* What is the rationale for replacing the UUIDs?
* What workflow are you all using where it doesn't matter that files that are downloaded aren't able to be uploaded?
    * What's the purpose of downloading then?
