### ISSUE TITLE
DEMISTO_SDK_IGNORE_CONTENT_WARNING not effective in repo without remote / remote named origin

### ISSUE THREAD

**Issue by maxgubler** [demisto/demisto-sdk#3526]
The environment variable was added with #2469 ... "to allow suppressing warnings when commands are not run under a content repo folder." This should apply to local repos without remotes.

The issue is located within the following lines:
https://github.com/demisto/demisto-sdk/blob/877b72dd592a8c95a427d8dd033571db003fc5ce/demisto_sdk/commands/common/tools.py#L2036-L2056

Specifically:
https://github.com/demisto/demisto-sdk/blob/877b72dd592a8c95a427d8dd033571db003fc5ce/demisto_sdk/commands/common/tools.py#L2042

A ValueError is raised by `git_repo.remote()` when no remote repo named `origin` is found. So, this issue actually applies to non-remote and non-origin-remote repos.

I suggest changing the line to:
``` python
try:
    remote_url = git_repo.remote().urls.__next__() 
except ValueError:
    remote_url = ""
```

With that, `is_fork_repo = "content" in remote_url ` will evaluate to `False`, and it'll proceed as intended, raising the `git.InvalidGitRepositoryError` (if there is no `.private-repo-settings` file).

**Comment by dorschw** [comment]
Hi @maxgubler, thanks for opening an issue. It is tracked internally as [XSUP-27659](https://jira-hq.paloaltonetworks.local/browse/XSUP-27659).

**Comment by eyalpalo** [comment]
Hi @maxgubler , a suggested fix is ready. We would like you to test this fix in order to validate it is working.
You can install the SDK from the branch I made (it’s the same as the published version, with this fix.) with the following command:
```pip install git+https://github.com/demisto/demisto-sdk.git@xsup_27659_no_remote#egg=demisto_sdk```
Make sure to uninstall it and reinstall the non-modified demisto-sdk (pip install demisto-sdk) after the testing is done.

**Comment by maxgubler** [comment]
#3606 appears to work; however, `DEMISTO_SDK_IGNORE_CONTENT_WARNING` isn't effective at "suppressing warnings" as it's supposed to here. https://github.com/demisto/demisto-sdk/blob/555aa337fc0bc28b12c0f1a47bd50a2ca8a3c055/demisto_sdk/commands/common/tools.py#L2031-L2033

The simple fix is to add the env variable check before the logger warning.

```py
        remote_url = ""
        if not os.getenv("DEMISTO_SDK_IGNORE_CONTENT_WARNING"):
            logger.warning(
                f"Could not find remote with name {GIT_UPSTREAM} for repo {git_repo.working_dir}"
            )
```

**Comment by eyalpalo** [comment]
This fix has been merged and will be released in the next release. The test branch I sent you @maxgubler will be deleted, so please reinstall the SDK in his last version until the new version is released.

**Comment by maxgubler** [comment]
Great, thank you
