### ISSUE TITLE
demisto-sdk zip pack not possible to import in demisto instance

### ISSUE THREAD

**Issue by chkp-christiang** [demisto/demisto-sdk#3562]
I'm trying to share a zipped pack in order to be tested in a different demisto instance where I have no access and then I cannot upload by using `demisto-sdk upload`.

I have tried generating the zip in different ways:

```
demisto-sdk unify -i Packs/MyPack  # generates Packs/MyPack/MyPack.zip
```
```
demisto-sdk zip-packs -i Packs/MyPack  # generates uploadable_packs/MyPack.zip
```
Uploading any of both content packs returns the error:
```
Could not import file. The file you are trying to import does not include a XSOAR signed Content Pack. You can only import Content Packs that have been provided by Cortex XSOAR
```
<img width="765" alt="image" src="https://github.com/demisto/demisto-sdk/assets/3923412/dff14ace-e268-4f7b-ba13-e104ee797240">

It is possible to create the content packs using the option documented here: https://github.com/demisto/demisto-sdk/tree/master/demisto_sdk/commands/create_artifacts, in this case it is possible to pass a `SIGN_DIRECTORY_PATH` or `SIGNATURE_KEY` but I don't have any.

Any help is highly appreciated.

**Comment by dorschw** [comment]
Hi, please contact PANW technical support, and provide them with the SDK logs.

**Comment by kgal-pan** [comment]
You can set `content.pack.verify:false` in [XSOAR configuration](https://docs-cortex.paloaltonetworks.com/r/Cortex-XSOAR/6.8/Cortex-XSOAR-Administrator-Guide/Modify-Server-Configurations).
