### ISSUE TITLE
demisto-sdk lint --console-log-threshold DEBUG vs ERROR no difference

### ISSUE THREAD

**Issue by ennozdd** [demisto/demisto-sdk#3661]
running demisto-lint is filling up the stdout with unnecessary information so I wanted to just see something useful and tried this argument but this argument either way is giving me the same result

demisto-sdk lint -i Packs/xxyyzz/Scripts/mytest  --console_log_threshold **DEBUG**  2>&1 | wc -l
89
demisto-sdk lint -i Packs/xxyyzz/Scripts/mytest  --console_log_threshold **ERROR**  2>&1 | wc -l
89
demisto-sdk --version
You are using demisto-sdk 1.20.2.

Does that mean the argument is not working as expected or does it mean this is not what I am looking for?

I want to see the part where it says 
`Passed Unit-tests:`
however this is being written in debug mode and I cannot print this out to the console with console-log-threshold DEBUG

**Comment by dorschw** [comment]
Hi Enes, please contact PANW support with this information.
