### ISSUE TITLE
demisto-sdk validet -g issue reaching remote repository

### ISSUE THREAD

**Issue by ckaadic** [demisto/demisto-sdk#3736]
This week I upgraded from demisto-sdk 1.20.1 to latest version (1.20.7). Since the upgrade demisto-sdk validate -g is not working anymore. It shows following error:

```
...
File ".../python3.10/site-packages/git/cmd.py", line 603, in wait
    raise GitCommandError(remove_password_if_present(self.args), status, errstr)
git.exc.GitCommandError: Cmd('git') failed due to: exit code(128)
  cmdline: git fetch -v -- origin
  stderr: 'fatal: Could not read from remote repository.'
```

When downgrading to 1.20.1 version again, the issue is gone. Installing the following versions one by one I was able to pin the issue occuring in 1.20.3 release.

**Comment by dorschw** [comment]
Please contact PANW technical support.
