### ISSUE TITLE
forced naming convention on output parameter

### ISSUE THREAD

**Issue by ThisIsNotTheUserYouAreLookingFor** [demisto/demisto-sdk#799]
Hi I'm trying to get this demisto-sdk working in a devcontainer,

> For consistency, we assume that for each integration or script the folder containing it will have the same name as the integration/script name with no separators. For example the integration Test Integration_Full-Name, will be under ~/.../content/Packs/TestPack/Integrations/TestIntegrationFullName/.

Why is this? I `demisto-sdk init` a package, and I just want to download an already existing integration in it. Why is the tool forcing a naming convention on me that makes no sense? I made the package with the tool in the first place!

**Comment by glicht** [comment]
@ThisIsNotTheUserYouAreLookingFor this assumption is for simplifying the way the download works.

I am not sure how you envision things should work. You are welcome to provide more details and we will see if it is possible to improve the way the sdk works.

**Comment by guyfreund** [comment]
@ThisIsNotTheUserYouAreLookingFor can you please attach a zip of the whole pack as in your dev-env?

**Comment by ThisIsNotTheUserYouAreLookingFor** [comment]
well, sure but it's pretty empty, what I did is very easy to simulate:
```
root ➜ /workspaces/soc-scripts/demisto $ demisto-sdk init
Please input the name of the initialized pack: BDExtensions
Creating pack base files
Successfully created the pack BDExtensions in: BDExtensions

Would you like fill pack's metadata file? Y/N N
Created pack metadata at path : BDExtensions/pack_metadata.json

Do you want to create an integration in the pack? Y/N N
root ➜ /workspaces/soc-scripts/demisto $ ls
BDExtensions
root ➜ /workspaces/soc-scripts/demisto $ cd BDExtensions/
/workspaces/soc-scripts/demisto/BDExtensions
root ➜ /workspaces/soc-scripts/demisto/BDExtensions $ ls
Classifiers  Dashboards      IncidentTypes    IndicatorTypes  Layouts    README.md  Scripts        Widgets    pack_metadata.json
Connections  IncidentFields  IndicatorFields  Integrations    Playbooks  Reports    TestPlaybooks  doc_files
root ➜ /workspaces/soc-scripts/demisto/BDExtensions $ cd ..
root ➜ /workspaces/soc-scripts/demisto $ demisto-sdk download -i 'BDQRadarExtensions' -o BDExtensions/
Path BDExtensions/ is not a valid Path pack. The designated output pack's path is of format ~/.../content/Packs/$PACK_NAME
```

I can send you the empty pack file if you really want it.

**Comment by guyfreund** [comment]
@ThisIsNotTheUserYouAreLookingFor I don't see here the integration name, and also the path you are working in isn't not true
`demisto-sdk download -i 'BDQRadarExtensions' -o BDExtensions/` should run in `~/.../content/Packs/` to work.

Please provide more details.

**Comment by ThisIsNotTheUserYouAreLookingFor** [comment]
@guyfreund The existing integration name is BDQRadarExtensions, which I try to download into the freshly created pack "BDExtensions". (see commands above). I have tried to create the path ~/.../content/Packs/ (if not to do manually, where is this part described in the wiki?) but didn't work either

**Comment by guyfreund** [comment]
@ThisIsNotTheUserYouAreLooking sorry for the late response.

The path needs to be under `~/.../Packs/$PACK_NAME`, then the integration name should follow the following assumption to make sure the download is done properly.

> For consistency, we assume that for each integration or script the folder containing it will have the same name as the integration/script name with no separators. For example the integration Test Integration_Full-Name, will be under ~/.../content/Packs/TestPack/Integrations/TestIntegrationFullName/.

 Unfortunately, for the moment we can't change the download command to work without this assumption.
I'm closing this issue, if the issue reproduces please re-open and we will try to assist.

Guy

**Comment by guyfreund** [comment]
@ThisIsNotTheUserYouAreLooking sorry for the late response.

What is the use-case of what you are trying to do?
Are the assumptions we take on the integration name is what interfere or is it the prefix of `content/Packs`?

Guy
