### ISSUE TITLE
[FEATURE] Request Simplified Support for split-yml

### ISSUE THREAD

**Issue by cmd-not-found** [demisto/demisto-sdk#810]
## Request

Request that `split-yml` command support a simplified command execution that does only its intended purpose. 

## Background

Currently, if you execute `demisto-sdk split-yml -i ~/myScript.yml -o Scripts/myScript`, the actual yml split occurs quickly and then the `demisto-sdk` begins the process of setting up the virtual env, configuring docker images, etc. The problem is that the sdk is making an assumption about the dev environment that isn't always accurate. For instance, a corporate network where developers utilize Windows workstations may not have ready access to execute Docker, which will cause the `demisto-sdk split-yml` command to fail but the actual *split* was successful. In that scenario, the developer may only use the `demisto-sdk` locally to split and unify where other checks may happen elsewhere, so the developer is forced to execute the command and then `CTRL-C` to stop it every time. 

The assumptions made about the dev environment seems to be a limiting factor. The command is described as splitting the yml - I feel like it should do that and that alone. It seems the `unify` command actually already executes in this way.

**Comment by Itay4** [comment]
@cmd-not-found thanks for the suggestion
in the split cmd, the docker is used to detect the python version, so we can then install the py requirements in the pyenv
the way i see it we can add 2 cmd args here:
1. python version (and by that avoid the check on the docker)
2. skip the py requirements installation completely

**Comment by cmd-not-found** [comment]
@Itay4 my vote would be to skip the pyenv installation option completely and/or break out that functionality into a dedicated command. Honestly though - a simple switch for the `split-yml` command to bypass would work also. That's all I really need.

**Comment by roysagi** [comment]
We already have `no-pipenv` functionality built, it is just not exposed. I'll simply add this as a possible flag.
