### ISSUE TITLE
[BUG] demisto-sdk update-release-notes cmd docs need updating

### ISSUE THREAD

**Issue by cmd-not-found** [demisto/demisto-sdk#815]
## Issue description

The docs for `demisto-sdk update-release-notes` aren't in line with current version. 

## Additional details

- The docs referenced below do not align to current `demisto-sdk` version. 

```
(venv) jberry@Metaverse content % demisto-sdk --version
demisto-sdk 1.2.4
```

> **REF:** https://github.com/demisto/demisto-sdk/tree/master/demisto_sdk/commands/update_release_notes#arguments

- Documented `-p` command

```
(venv) jberry@Metaverse content % demisto-sdk update-release-notes -p MyPack -u minor
Usage: demisto-sdk update-release-notes [OPTIONS]

Error: no such option: -p
```

- Output of `-h` command below. I only figured out the proper syntax for `-p` (actually `-i`) by looking at the code [here](https://github.com/demisto/demisto-sdk/blob/0220e420c91b5989dd3679baf1e1fc135861b80b/demisto_sdk/__main__.py#L820) and then also realized there should be a `-h` exposed for the command itself (also not documented). 

```
(venv) jberry@Metaverse content % demisto-sdk update-release-notes -h

Usage: demisto-sdk update-release-notes [OPTIONS]

Options:
  -h, --help                     Show this message and exit.
  -i, --input TEXT               The path of the content pack.
  -u, --update_type UPDATE_TYPE  The type of update being done. [major, minor, revision,
                                 maintenance, documentation]

  -v, --version TEXT             Bump to a specific version.
  --all                          Update all changed packs
  --text TEXT                    Text to add to all of the release notes files
  --pre_release                  Indicates that this change should be designated a pre-release
                                 version.

  -idp, --id-set-path PATH       The path of the id-set.json used for APIModule updates.
```

**Comment by Itay4** [comment]
@cmd-not-found thanks for reporting this
it was fixed in https://github.com/demisto/demisto-sdk/pull/816/files
